### PR TITLE
feature/beautify-attributes

### PR DESCRIPTION
**Pull request by wmhilton**
Hi, would you be interested in any of these changes?

- feat(*): trim attributes
- feat(*): remove empty attributes
- feat(*): neatly format style attributes

And yes, I'm dealing with some *ghastly* HTML code. :) I kid you not, a mix of tabs and spaces *in the attributes*.

### CODE REVIEW

**Comment by GitScrum** [comment]
@wmhilton Hi, What is use case for it?

**Comment by wmhilton** [comment]
I am trying to clean up some really janky HTML source code that has these problems.

**Comment by GitScrum** [comment]
feat(*): trim attributes - return `attrsBoolean` name
feat(*): remove empty attributes - This should be an option
feat(*): neatly format style attributes - remove, [see my response](https://github.com/GitScrum/posthtml-beautify/issues/163)

**Comment by wmhilton** [comment]
> feat(): trim attributes - return attrsBoolean name

will do!

> feat(): remove empty attributes - This should be an option, by default false and add test for this.

will do if I find time

**Pull request closed without merging**
